export const SET_ALERT='SET_ALERT';
export const REMOVE_ALERT='REMOVE_ALERT';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_SUCCESS_HOS='REGISTER_SUCCESS_HOS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const USER_LOADED='USER_LOADED'
export const USER_LOADED_HOS='USER_LOADED_HOS'
export const AUTH_ERROR='AUTH_ERROR'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_SUCCESS_HOS='LOGIN_SUCCESS_HOS'
export const LOGIN_FAIL='LOGIN_FAIL'
export const LOGOUT='LOGOUT'
export const GET_PROFILE='GET_PROFILE'
export const GET_PROFILES='GET_PROFILES'
export const UPDATE_PROFILE='UPDATE_PROFILE'
export const PROFILE_ERROR='PROFILE_ERROR'
export const CLEAR_PROFILE='CLEAR_PROFILE'
export const DELETE_ACCCOUNT='DELETE_ACCOUNT'
export const GET_POSTS='GET_POSTS'
export const GET_POST='GET_POST'
export const POST_ERROR='POST_ERROR'
export const ADD_PARTICPANTS='ADD_PARTICIPANTS'
export const REMOVE_PARTICPANTS='REMOVE_PARTICIPANTS'
export const ADD_POST='ADD_POST'
export const DELETE_POST='DELETE_POST'
export const ADD_REQUEST='ADD_REQUEST'
export const DELETE_REQUEST='DELETE_REQUEST'
export const ACCEPT_REQUEST='ACCEPTS_REQUEST'
export const GET_REQUESTS='GET_REQUESTS'
export const GET_REQUEST='GET_REQUEST'
export const REJECT_REQUEST='REJECT_REQUEST'



